apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  namespace: auth
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
  selector:
    app: authentication