apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: postgress-pvc
 labels:
   app: postgres
spec:
 storageClassName: manual
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 1Gi