apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-data-pv
  labels:
    type: pgadmin
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/pgadmin-data"
