apiVersion: v1
kind: Pod
metadata:
 name: db-pod
 labels:
   app: postgres
   name: postgres-pod
spec:
 containers:
   - image: vladandreiy/postgres:v1
     imagePullPolicy: Always
     name: postgres
     volumeMounts:
     - name: myvol
       mountPath: /etc/config
     ports:
       - containerPort: 5432
     env:
        - name: POSTGRES_USER
          value: "ccstudent"
        - name: POSTGRES_PASSWORD
          value: "123"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        - name: POSTGRES_HOST
          value: "db"
 volumes:
   - name: myvol
     persistentVolumeClaim:
       claimName: postgress-pvc