apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-manager-deployment
  labels:
    app: product-manager
  namespace: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-manager
  template:
    metadata:
      labels:
        app: product-manager
    spec:
      containers:
      - name: product-manager
        image: vladandreiy/product-manager:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
          - name: POSTGRES_USER
            value: "ccstudent"
          - name: POSTGRES_PASSWORD
            value: "123"
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
          - name: POSTGRES_HOST
            value: "db"