# Generated by Django 4.1.7 on 2023-06-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_firstname_order_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_token',
        ),
    ]
